defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
seed: 0
data:
  type: "two_moons"
  train_samples: 300
  val_samples: 300
  test_samples: 300
  batch_size: 30
model:
  input_size: 2
  hidden_layer_size: 20
  optimizer:
    lr: 1e-3
trainer:
  max_epochs: 100

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val_acc" # quantity to be monitored, must be specified !!!
  min_delta: 0. # minimum change in the monitored quantity to qualify as an improvement
  patience: 3 # number of checks with no improvement after which training will be stopped
  verbose: False # verbosity mode
  mode: "max" # "max" means higher metric value is better, can be also "min"
  strict: True # whether to crash the training if monitor is not found in the validation metrics
  check_finite: True # when set True, stops training when the monitor becomes NaN or infinite
  stopping_threshold: null # stop training immediately once the monitored quantity reaches this threshold
  divergence_threshold: null # stop training as soon as the monitored quantity becomes worse than this threshold
  check_on_train_epoch_end: null # whether to run early stopping at the end of the training epoch
  # log_rank_zero_only: False  # this keyword argument isn't available in stable version